FROM docker.io/library/golang AS builder
lABEL matainer="Naing Ye Minn <naingyeminn@gmail.com>"

WORKDIR /go/src
COPY todo-api.go .
RUN export CGO_ENABLED=0 && \
    go mod init todoapp/todo-api && \
    go mod tidy && \
    go build 

FROM docker.io/library/alpine
lABEL matainer="Naing Ye Minn <naingyeminn@gmail.com>" \
      description="Required Environment Variables: DB_USER, DB_PASS, DB_HOST, DB_PORT, DB_NAME"
WORKDIR /app
COPY --from=builder /go/src/todo-api /app

CMD ["/app/todo-api"]
